<a href="https://colab.research.google.com/github/Balramt/PyTorch/blob/main/experiments/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch


In [3]:
import torch
print(torch.__version__)

2.10.0+cpu


In [4]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


In [7]:
# using empty
a = torch.empty(2,3)
a

tensor([[2.5659e+00, 0.0000e+00, 2.4939e+00],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

In [8]:
# check type
type(a)

torch.Tensor

In [9]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# using rand  provide random values between o to 1
torch.rand(2,3)

tensor([[0.4014, 0.5101, 0.1358],
        [0.2362, 0.2971, 0.9803]])

In [13]:
# use of seed
torch.rand(2,3)

tensor([[0.6537, 0.7169, 0.8088],
        [0.2509, 0.7034, 0.5804]])

In [14]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
# SO here by using seed we reproduce the same random variable
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])