<a href="https://colab.research.google.com/github/Balramt/PyTorch/blob/main/experiments/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch


In [3]:
import torch
print(torch.__version__)

2.10.0+cpu


In [4]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


In [7]:
# using empty
a = torch.empty(2,3)
a

tensor([[2.5659e+00, 0.0000e+00, 2.4939e+00],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

In [8]:
# check type
type(a)

torch.Tensor

In [9]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# using rand  provide random values between o to 1
torch.rand(2,3)

tensor([[0.4014, 0.5101, 0.1358],
        [0.2362, 0.2971, 0.9803]])

In [13]:
# use of seed
torch.rand(2,3)

tensor([[0.6537, 0.7169, 0.8088],
        [0.2509, 0.7034, 0.5804]])

In [14]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
# SO here by using seed we reproduce the same random variable
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
# using tensor  used to dervive custome tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
# other ways

# arange,  it will arrange 0 to 10 with gap 2
print("using arange ->", torch.arange(0,10,2))

# using linspace, it will create  linear space of  9 between o to 10
print("using linspace ->", torch.linspace(0,10,9))

# using eye, It will create the identity metrix of 5 by 5
print("using eye ->", torch.eye(5))

# using full, it will create the sape of 3 by 2 with everyitem is 5
print("using full ->", torch.full((3, 2), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.2500,  2.5000,  3.7500,  5.0000,  6.2500,  7.5000,  8.7500,
        10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5],
        [5, 5],
        [5, 5]])


Tensor Shapes

In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x.shape

torch.Size([2, 3])

In [22]:
# Below is used to create empty tensor with same like above tensor (X) (2 By 3)
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6066965718240341302, 3832908758036133424, 6500719774110464302]])

In [23]:
# It will create zeros tensor with same shape of x
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [26]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [28]:
# it will not create the tensor of same x shape beacue x is integer values where rand generates float values
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [29]:
# it create the x shape tensor with random values with float beacuse we give the directions
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

Tensor Data Types

In [30]:
# find data type
x.dtype

torch.int64

In [32]:
# assign data type, so here you saw we create the tesnor with float values with integer data  types ok
torch.tensor([1.0,2.0,3.0,4.5,5.4,6.6], dtype=torch.int32)

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [33]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [41]:
# using to(), this wil change the data types of x with int 64 to float 32
x32 = x.to(torch.float32)
x32

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [42]:
x32.dtype

torch.float32

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


**Mathematical operations**

**1. Scalar operation**

In [46]:
# Here we created tensor with random values
x = torch.rand(2,2)
x

tensor([[0.7445, 0.4892],
        [0.2426, 0.7003]])

In [47]:
x.dtype

torch.float32

Below are some scalar operations performed on tensor x

In [53]:
# addition
x + 2

tensor([[2.7445, 2.4892],
        [2.2426, 2.7003]])

In [49]:
# substraction
x - 2

tensor([[-1.2555, -1.5108],
        [-1.7574, -1.2997]])

In [50]:
# multiplication
x * 3

tensor([[2.2335, 1.4676],
        [0.7277, 2.1010]])

In [51]:
# int division
(x * 100)//3

tensor([[24., 16.],
        [ 8., 23.]])

In [52]:
# power
x**2

tensor([[0.5543, 0.2393],
        [0.0588, 0.4905]])

Now we will see if we have two or more tensor thne How we can perform element wise operations


**2. Element wise operation**